app/stories/forms.py
#!/usr/bin/python
# -*- UTF-8 -*-

from flask_wtf import Form
from wtforms import TextAreaField, StringField, PasswordField, SelectField, validators, ValidationError
from wtforms.validators import DataRequired

class BulkAddStepForm(Form):
    steps = TextAreaField('Steps', validators = [DataRequired()])

app/users/forms.py
#!/usr/bin/python
# -*- UTF-8 -*-

from flask_wtf import Form
from wtforms import StringField, PasswordField, SelectField, validators, ValidationError
from wtforms.validators import DataRequired

class EditUserForm(Form):
    username = StringField('Username', validators = [DataRequired()])
    password = PasswordField('Password', validators=[validators.EqualTo('confirm', message="Password must match")])
    confirm = PasswordField('Password')
    email = StringField('Email', validators=[validators.Email('Invalid email address.')])
    role_id = SelectField('Role', coerce=int)

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')

app/stories/__init__.py
#!/usr/bin/python
# -*- UTF-8 -*-
from flask import Blueprint

stories = Blueprint('stories', __name__)

#from . import forms
from . import views

app/stories/views.py
#!/usr/bin/python
# -*- UTF-8 -*-

from . import stories
from ..decorators import permission_required
from ..models import Permission, Story, Step, User, InstanceStory, HistoryInstance
from .forms import BulkAddStepForm
from .. import db
from flask import request, redirect, url_for, render_template, Response, session, Markup, flash, abort
from flask.ext.login import current_user, login_required
from graphviz import Digraph
import markdown
import datetime

def is_obj_of_current_user(story):
    return story.user_id == current_user.id

def flash_redirect(message, category, route):
    flash(message, category)
    return redirect(url_for(route))

@stories.route('/<int:story_id>/bulk_add_step', methods = ['GET', 'POST'])
@login_required
@permission_required(Permission.CREATE_STORY)
def add_bulk_steps(story_id):
    story = Story.query.get_or_404(story_id)
    if is_obj_of_current_user(story):
        form = BulkAddStepForm()
        if form.validate_on_submit():
            content = form.steps.data
            for line in content.split("\n"):
                sep_pos = line.strip().find(':')
                step_name = line[:sep_pos]
                step_content = line[sep_pos+1:].strip()
                new_step = Step(step_name, step_content, story_id)
                db.session.add(new_step)
            db.session.commit()
            return redirect(url_for('stories.show_story', story_id = story_id))
        return render_template('stories/bulk_add_step.html', story_id = story_id, form = form)
    else:
        return flash_redirect('The story does not belong to you', 'error', 'main.index')

@stories.route('/<int:user_id>')
def show(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('stories/list.html', stories = user.stories, user = user)

@stories.route('/<int:user_id>/new', methods=['GET', 'POST'])
@stories.route('/new', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.CREATE_STORY)
def new(user_id = None):
    if user_id is None:
        user_id = current_user.id
    if request.method == "POST":
        name = request.form['name']
        story = Story(name, user_id)
        db.session.add(story)
        db.session.commit()
        return redirect(url_for('stories.show_story', story_id = story.id))
    return render_template("stories/new.html", user_id = user_id)

@stories.route('/show/<int:story_id>')
@login_required
@permission_required(Permission.CREATE_STORY)
def show_story(story_id):
    story = Story.query.get_or_404(story_id)
    if is_obj_of_current_user(story):
        return render_template('stories/show.html', story = story)
    else:
        return flash_redirect('The story does not belong to you', 'error', 'main.index')

@stories.route('/<int:story_id>/new_step', methods = ['GET', 'POST'])
@login_required
@permission_required(Permission.CREATE_STORY)
def new_step(story_id):
    steps = Step.query.filter_by(story_id = story_id).all()
    story = Story.query.get_or_404(story_id)
    if is_obj_of_current_user(story):
        if request.method == "POST":
            step = Step(request.form['name'], request.form['content'], story_id)
            step.first_choice = request.form['first_choice_text']
            step.first_choice_step_id = request.form['first_choice']
            step.second_choice = request.form['second_choice_text']
            step.second_choice_step_id = request.form['second_choice']
            if "final_step" in request.form:
                step.final = request.form['final_step'] == "on"
            else:
                step.final = False
            db.session.add(step)
            db.session.commit()
            return redirect(url_for('stories.show_step', step_id = step.id))
        return render_template('stories/new_step.html', story_id = story_id, steps = steps)
    else:
        return flash_redirect('The story does not belong to you', 'error', 'main.index')

@stories.route('/<int:story_id>/start')
@login_required
def start_story(story_id):
    story = Story.query.get_or_404(story_id)
    instance = InstanceStory(story.id, session['user_id'], story.initial_step_id)
    db.session.add(instance)
    db.session.commit()
    history = HistoryInstance(instance.id, None, story.initial_step_id, None)
    db.session.add(history)
    db.session.commit()
    return redirect(url_for('stories.show_instance', instance_id = instance.id))

@stories.route('/<int:instance_id>/play')
@stories.route('/<int:instance_id>/play/<int:choice>')
@login_required
def show_instance(instance_id, choice = None):
    instance = InstanceStory.query.get_or_404(instance_id)
    if 'user_id' in session and instance.user_id == int(session['user_id']):
        step = Step.query.get_or_404(instance.current_step_id)
        if choice:
            if choice == 1:
                from_step_id = step.id
                choice_text = step.first_choice
                step = Step.query.get_or_404(step.first_choice_step_id)
                history = HistoryInstance(instance.id, from_step_id, step.id, choice_text)
                instance.current_step_id = step.id
                if step.final:
                    instance.finished_timestamp = datetime.datetime.now()
                    instance.finished = True
                db.session.add(history)
                db.session.commit()
            elif choice == 2:
                from_step_id = step.id
                choice_text = step.second_choice
                step = Step.query.get_or_404(step.second_choice_step_id)
                history = HistoryInstance(instance.id, from_step_id, step.id, choice_text)
                instance.current_step_id = step.id
                if step.final:
                    instance.finished_timestamp = datetime.datetime.now()
                    instance.finished = True
                db.session.add(history)
                db.session.commit()
        content = Markup(markdown.markdown(step.content))
        return render_template('/steps/play.html', content = content, story = instance.story, step = step, instance_id = instance_id)
    else:
        return flash_redirect('This is not your story! %s != %s' % (str(type(instance.user_id)), str(type(session['user_id']))), 'main.index')

@stories.route('/')
def list():
    stories = Story.query.all()
    return render_template('stories/all.html', stories = stories)

@stories.route('/schema-<int:story_id>.dot')
@login_required
def generate_dot(story_id):
    story = Story.query.get_or_404(story_id)
    res = Response()
    g = Digraph(story.name)
    for step in story.steps:
        if step.final:
            g.node('step_%d' % step.id, label=step.name, color="lightblue2", style="filled")
        else:
            g.node('step_%d' % step.id, label=step.name)
        if step.first_choice_step_id:
            g.edge('step_%d' % step.id, 'step_%d' % step.first_choice_step_id, label = step.first_choice)
        if step.second_choice_step_id:
            g.edge('step_%d' % step.id, 'step_%d' % step.second_choice_step_id, label = step.second_choice)
    if str(request.url_rule).endswith('dot'):
        res.content_type = "text/plain"
        res.data = g.source
    elif str(request.url_rule).endswith('png'):
        g.format = 'png'
        res.content_type = 'image/png'
        res.data = g.pipe()
    return res

@stories.route('/schema-<int:story_id>.png')
@login_required
def generate_png(story_id):
    story = Story.query.get_or_404(story_id)
    res = Response()
    g = Digraph(story.name)
    for step in story.steps:
        if step.final:
            g.node('step_%d' % step.id, label=step.name, color="lightblue2", style="filled")
        else:
            g.node('step_%d' % step.id, label=step.name)
        if step.first_choice_step_id:
            g.edge('step_%d' % step.id, 'step_%d' % step.first_choice_step_id, label = step.first_choice)
        if step.second_choice_step_id:
            g.edge('step_%d' % step.id, 'step_%d' % step.second_choice_step_id, label = step.second_choice)
    if str(request.url_rule).endswith('dot'):
        res.content_type = "text/plain"
        res.data = g.source
    elif str(request.url_rule).endswith('png'):
        g.format = 'png'
        res.content_type = 'image/png'
        res.data = g.pipe()
    return res

@stories.route('/<int:story_id>/set_init/<int:step_id>')
@login_required
@permission_required(Permission.CREATE_STORY)
def set_initial_step(story_id, step_id):
    story = Story.query.get_or_404(story_id)
    if is_obj_of_current_user(story):
        step = Step.query.get_or_404(step_id)
        if step.story_id == story.id:
            story.initial_step_id = step.id
            db.session.commit()
            flash('The initial step of the story %d have been changed.' % story.id, 'info')
        else:
            flash('The step %d is not a step of story %d' % (step.id, story.id), 'error')
        return redirect(url_for('stories.show_story', story_id = story.id))
    else:
        return flash_redirect('The story does not belong to you', 'error', 'main.index')

@stories.route('/<int:story_id>/remove_init/<int:step_id>')
@login_required
@permission_required(Permission.CREATE_STORY)
def remove_initial_step(story_id, step_id):
    story = Story.query.get_or_404(story_id)
    if is_obj_of_current_user(story):
        step = Step.query.get_or_404(step_id)
        if step.story_id == story.id and story.initial_step_id == step.id:
            story.initial_step_id = None
            db.session.commit()
            flash('The initial step of the story %d have been removed.' % story.id, 'info')
        else:
            flash('The step %d is not a step of story %d or the initial step of story %d' % (step.id, story.id, story.id), 'error')
        return redirect(url_for('stories.show_story', story_id = story.id))
    else:
        return flash_redirect('The story does not belong to you', 'error', 'main.index')


@stories.route('/step/<int:step_id>')
@login_required
def show_step(step_id):

app/users/__init__.py
#!/usr/bin/python
# -*- UTF-8 -*-
from flask import Blueprint

users = Blueprint('users', __name__)

#from . import forms
from . import views

app/users/views.py
#!/usr/bin/python
# -*- UTF-8 -*-

from . import users
from .forms import EditUserForm
from ..models import User, Role
from .. import db
from ..decorators import admin_required
from flask.ext.login import login_required
from flask import render_template, request, redirect, url_for, flash, current_app

@users.route('/<int:user_id>')
def show(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('users/show.html', user = user)

@users.route('/add', methods=['GET', 'POST'])
@admin_required
def add():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        user = User(username, email)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.show', user_id = user.id))
    return render_template('users/add.html')

@users.route('/<int:user_id>/edit', methods = ['GET', 'POST'])
@login_required
@admin_required
def edit(user_id):
    user = User.query.get_or_404(user_id)
    form = EditUserForm(request.form, obj = user)
    roles = [(r.id, r.name) for r in Role.query.order_by('name')]
    form.role_id.choices = roles
    if request.method == "POST" and form.validate_on_submit:
        modification_detected = []
        if user.username != form.username.data:
            user.username = form.username.data
            modification_detected.append('username')
        if user.email != form.email.data:
            user.email = form.email.data
            modification_detected.append('email')
        if form.password.data is not None and not form.password.data == "" and form.password.data == form.confirm.data:
            user.password = form.password.data
            modification_detected.append('password')
        if user.role_id != form.role_id.data:
            user.role_id = form.role_id.data
            modification_detected.append('role')
        db.session.commit()
        if len(modification_detected) > 0:
            message = 'User %s have been updated:<ul>' % user.username
            for modif in modification_detected:
                message += "<li>%s</li>" % modif
            message += "</ul>"
            flash(message)
            return redirect(url_for('users.list'))
        else:
            flash('No modification have been detected for user %s' % user.username, "warning")
    return render_template('users/edit.html', user = user, form = form)

@users.route('/')
@admin_required
def list():
    users = User.query.all()
    return render_template('users.html', users = users, current_app = current_app)


@users.route('/<int:user_id>/delete')
def delete(user_id):
    user = User.query.get_or_404(user_id)
    message = 'User %r deleted' % user
    db.session.delete(user)
    db.session.commit()
    flash(message)
    return redirect(url_for('users.list'))

app/templates/stories/_stories.html
<table class="table table-stripped">
	<tr>
		<th>Story Name</th>
		<th># Steps</th>
		<th>Timestamp</th>
	</tr>
	{% for story in stories %}
	<tr>
		<td>
			<a href="{{url_for('stories.show_story', story_id = story.id)}}">
				{{story.name}}
			</a>
		</td>
		<td>{{story.steps | length}}</td>
		<td>{{story.timestamp}}</td>
	</tr>
	{% endfor %}
</table>

app/templates/stories/all.html
{% extends "layout.html" %}
{% block content %}
<div class="panel panel-default">
	<div class="panel-heading">Available stories</div>
	<div class="panel-body">
		<ul class="list-group">
			{% for story in stories %}
			<li class="list-group-item">{{story.name}} (current play: {{story.instances.filter_by(finished=False).all()|length}}){% if current_user.is_authenticated %}: <a href="{{url_for('stories.start_story', story_id = story.id)}}">Start</a>{% endif %}<br />
				<img src="{{url_for('stories.generate_png', story_id = story.id)}}" alt="story-{{story.id}}" />
			</li>
			{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}

app/templates/stories/bulk_add_step.html
{% extends "layout.html" %}
{% block content %}
<div class="page-header">
		<h1>Bulk add steps for {{story_id}}</h1>
</div>
<form action="{{url_for('stories.add_bulk_steps', story_id = story_id)}}" method="post">
	{{form.csrf_token()}}	 
	<div class="form-group">
		{{form.steps.label}}<br />
		{{form.steps(class="form_control",cols=70, rows=10)}}
		<span id="stepsHelp" class="help-block">
			The format of the line is <em>step name: content</em>
		</span>
	</div>
	<div>
		<button class="btn btn-primary">Bulk add</button>
	</div>
</form>
{% endblock %}

app/templates/stories/list.html
{% extends "layout.html" %}
{% block content %}
		<h2>Stories of user {{user.username}}</h2>
		<ul>
			{% for story in stories %}
			<li><a href="{{url_for('stories.show_story', story_id = story.id)}}">{{story.name}}</a> with {{story.steps | length}} steps ({{story.timestamp}})</li>
			{% endfor %}
		</ul>

		<a href="{{url_for('stories.new', user_id = user.id)}}">New story</a>
{% endblock %}

app/templates/stories/new.html
{% extends "layout.html" %}
{% block content %}
		<form action="{{url_for('stories.new', user_id = user_id)}}" method="post">
			<div>
				<label for="name">Name:</label>
				<input id="name" type="text" name="name" />
			</div>
			<div>
				<button>Add new story</button>
			</div>
		</form>
{% endblock %}

app/templates/stories/new_step.html
{% extends "layout.html" %}
{% block content %}
		<form action="{{url_for('stories.new_step', story_id = story_id)}}" method="post">
			<div>
				<label for="name">Name:</label>
				<input id="name" type="text" name="name" />
			</div>
			<div>
				<label for="content">Content:</label>
				<textarea id="content" name="content" cols="30" rows="10"></textarea>
			</div>
			<div>
				<label for="first_choice_text">First choice text</label>
				<input id="first_choice_text" type="text" name="first_choice_text" />

				<label for="first_choice">Step</label>
				<select id="first_choice" name="first_choice">
					<option value="">None</option>
					{% for step in steps %}
					<option value="{{step.id}}">{{step.name}}</option>
					{% endfor %}
				</select>
			</div>
			<div>
				<label for="second_choice_text">Second choice text</label>
				<input id="second_choice_text" type="text" name="second_choice_text" />

				<label for="second_choice">Step</label>
				<select id="second_choice" name="second_choice">
					<option value="">None</option>
					{% for step in steps %}
					<option value="{{step.id}}">{{step.name}}</option>
					{% endfor %}
				</select>
			</div>
			<div>
				<label for="final_step">Final Step?</label>
				<input id="final_step" type="checkbox" name="final_step" />
			</div>
			<div>
				<button>Submit</button>
			</div>
		</form>
{% endblock %}

app/templates/stories/show.html
{% extends "layout.html" %}
{% block content %}
<div class="page-header">
		<h1>{{story.name}} <small>by {{story.user.username}}, created {{story.timestamp}}</small></h1>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		Steps
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<tr>
				<th>Name</th>
				<th>Choice 1 Text</th>
				<th>Choice 1 Step</th>
				<th>Choice 2 Text</th>
				<th>Choice 2 Step</th>
				<th>Final</th>
				<th>Actions</th>
			</tr>
		{% for step in story.steps %}
			{% if step.final %}
			{% set line_style = "info" %}
			{% elif step.id == story.initial_step_id %}
			{% set line_style = "success" %}
			{% else %}
			{% set line_style = None %}
			{% endif %}
			<tr {% if line_style %}class="{{line_style}}"{%endif%}>
				<td><a href="{{url_for('stories.show_step', step_id = step.id)}}">{{step.name}}</a></td>
				<td>{{step.first_choice}}</td>
				<td>{{step.first_choice_step_id}}</td>
				<td>{{step.second_choice}}</td>
				<td>{{step.second_choice_step_id}}</td>
				<td>{{step.final}}</td>
				<td>
					<a href="{{url_for('stories.edit_step', step_id = step.id)}}">Edit {{display_icon('edit')}}</a><br />
					<a href="{{url_for('stories.delete_step', step_id = step.id)}}">Delete {{display_icon('remove')}}</a><br />
					{% if step.id == story.initial_step_id %}
					<a href="{{url_for('stories.remove_initial_step', step_id = step.id, story_id = story.id)}}">Remove initial step {{display_icon('remove')}}</a>
					{% else %}
					<a href="{{url_for('stories.set_initial_step', step_id = step.id, story_id = story.id)}}">Set initial step {{display_icon('ok')}}</a>
					{% endif %}
				</td>
			</tr>
		{% endfor %}
		<tr>
			<td colspan="7">
				<a href="{{url_for('stories.new_step', story_id = story.id)}}">{{display_icon('plus')}} New step</a>
			</td>
		<tr>
		</tr>
			<td colspan="7">
				<a href="{{url_for('stories.add_bulk_steps', story_id = story.id)}}">{{display_icon('plus')}} Add bulk steps</a>
			</td>
		</tr>
		</table>
	</div>
</div>
<div class="panel panel-default">
	{% set instances = story.instances.all() %}
	<div class="panel-heading">Instances ({{instances|length}})</div>
	<div class="panel-body">
		<ul>
		{% for instance in instances %}
		<li>
			<a href="{{url_for('stories.show_instance', instance_id = instance.id)}}">{{instance.user.username}} @ {{instance.started}}</a>
		</li>
		{% endfor %}
		</ul>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		Story schema
	</div>
	<div class="panel-body">
		<img src="{{url_for('stories.generate_png', story_id = story.id)}}" alt="Schema of story {{story.id}}" />
	</div>
</div>
{% endblock %}

app/templates/stories/user.html
{% extends "layout.html" %}
{% block content %}
		<h2>My stories</h2>
		{% include 'stories/_stories.html' %}
		<a href="{{url_for('stories.new', user_id = user.id)}}">New story</a>
{% endblock %}