app/users/forms.py
#!/usr/bin/python
# -*- UTF-8 -*-

from flask_wtf import Form
from wtforms import StringField, PasswordField, SelectField, validators, ValidationError
from wtforms.validators import DataRequired

class EditUserForm(Form):
    username = StringField('Username', validators = [DataRequired()])
    password = PasswordField('Password', validators=[validators.EqualTo('confirm', message="Password must match")])
    confirm = PasswordField('Password')
    email = StringField('Email', validators=[validators.Email('Invalid email address.')])
    role_id = SelectField('Role', coerce=int)

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')

app/users/__init__.py
#!/usr/bin/python
# -*- UTF-8 -*-
from flask import Blueprint

users = Blueprint('users', __name__)

#from . import forms
from . import views

app/users/views.py
#!/usr/bin/python
# -*- UTF-8 -*-

from . import users
from .forms import EditUserForm
from ..models import User, Role
from .. import db
from ..decorators import admin_required
from flask.ext.login import login_required
from flask import render_template, request, redirect, url_for, flash, current_app

@users.route('/<int:user_id>')
def show(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('users/show.html', user = user)

@users.route('/add', methods=['GET', 'POST'])
@admin_required
def add():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        user = User(username, email)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.show', user_id = user.id))
    return render_template('users/add.html')

@users.route('/<int:user_id>/edit', methods = ['GET', 'POST'])
@login_required
@admin_required
def edit(user_id):
    user = User.query.get_or_404(user_id)
    form = EditUserForm(request.form, obj = user)
    roles = [(r.id, r.name) for r in Role.query.order_by('name')]
    form.role_id.choices = roles
    if request.method == "POST" and form.validate_on_submit:
        modification_detected = []
        if user.username != form.username.data:
            user.username = form.username.data
            modification_detected.append('username')
        if user.email != form.email.data:
            user.email = form.email.data
            modification_detected.append('email')
        if form.password.data is not None and not form.password.data == "" and form.password.data == form.confirm.data:
            user.password = form.password.data
            modification_detected.append('password')
        if user.role_id != form.role_id.data:
            user.role_id = form.role_id.data
            modification_detected.append('role')
        db.session.commit()
        if len(modification_detected) > 0:
            message = 'User %s have been updated:<ul>' % user.username
            for modif in modification_detected:
                message += "<li>%s</li>" % modif
            message += "</ul>"
            flash(message)
            return redirect(url_for('users.list'))
        else:
            flash('No modification have been detected for user %s' % user.username, "warning")
    return render_template('users/edit.html', user = user, form = form)

@users.route('/')
@admin_required
def list():
    users = User.query.all()
    return render_template('users.html', users = users, current_app = current_app)


@users.route('/<int:user_id>/delete')
def delete(user_id):
    user = User.query.get_or_404(user_id)
    message = 'User %r deleted' % user
    db.session.delete(user)
    db.session.commit()
    flash(message)
    return redirect(url_for('users.list'))

app/templates/debug.html
{% extends "layout.html" %}
{% block content %}
Login as
<ul>
	{% for user in users %}
	<li>
		<a href="{{url_for('auth.login_username', user = user.username)}}">{{user.username}}</a>
	</li>
	{% endfor %}
</ul>
<table>
	<tr>
		<th>String</th>
		<th>Endpoint</th>
		<th>Default</th>
		<th>Arguments</th>
		<th>Link</th>
	</tr>
	{% for url in urls.iter_rules() %}
	<tr>
		<td>{{url.string}}</td>
		<td>{{url.endpoint}}</td>
		<td>{{url.defaults}}</td>
		<td>
			<ul>
				{% for arg in url.arguments %}
				<li>{{arg}}</li>
				{% endfor %}
			</ul>
		</td>
		{% if url.arguments|length == 0 %}
		<td>
			<a href="{{url_for(url.endpoint)}}">{{url.rule}}</a>
		</td>
		{% else %}
		<td>
			{{url.rule}}
		</td>
		{% endif %}
	</tr>
	{% endfor %}
	</ul>
</table>

{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% block content %}
{% endblock %}

app/templates/instance_history.html
{% extends "layout.html" %}
{% block content %}
<div class="page-header">
<h1>
	History of an instance of {{instance.story.name}}
</h1>
</div>
<img src="{{url_for('stories.display_history_png', instance_id = instance.id)}}" alt="History" />
{% endblock %}

app/templates/instances.html
{% extends "layout.html" %}
{% macro display_instance(instance) %}
<li class="list-group-item"><strong>{{instance.story.name}}</strong> started by {{instance.user.username}} @ {{instance.started}} 
	{% if instance.finished %}and finished {{instance.finished_timestamp}} {% endif %}(<a href="{{url_for('stories.delete_instance', instance_id = instance.id)}}">Delete</a>), <a href="{{url_for('stories.display_history', instance_id = instance.id)}}">{{display_icon('film')}} Display history</a>:
	<ul>
		{% for history in instance.history.order_by(HistoryInstance.timestamp.asc()) %}
		{% if history.from_step_id %}
		<li>{{history.from_step_id}} to {{history.to_step_id}} @ {{history.timestamp}} by choosing <strong>{{history.choice_text}}</strong></li>
		{% else %}
		<li>Start at {{history.to_step_id}} @ {{history.timestamp}}</li>
		{% endif %}
		{% endfor %}
	</ul>
	{% if not instance.finished %}
		<a href="{{url_for('stories.show_instance', instance_id = instance.id)}}">{{display_icon('play')}} Continue</a>
	{% endif %}
</li>
{% endmacro %}
{% block content %}
<div class="page-header">
	<h1>Instances</h1>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Ongoing instances</div>
	<div class="panel-body">
		<ul class="list-group">
			{% for instance in instances %}
			{% if not instance.finished %}
			{{display_instance(instance)}}
			{% endif %}
			{% endfor %}
		</ul>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Finished instances</div>
	<div class="panel-body">
		<ul class="list-group">
			{% for instance in instances %}
			{% if instance.finished %}
			{{display_instance(instance)}}
			{% endif %}
			{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}

app/templates/layout.html
{% macro display_nav_link(target, label, icon=None) %}
{% if request.url_rule.endpoint == target %}
<li class="active">
	<a href="{{url_for(target, **kwargs)}}">
		{% if icon %}{{display_icon(icon)}}{% endif %}
		{{label}} <span class="sr-only">(current)</span>
	</a>
</li>
{% else %}
<li>
	<a href="{{url_for(target, **kwargs)}}">
		{% if icon %}{{display_icon(icon)}}{% endif %}
		{{label}}
	</a>
</li>
{% endif %}
{% endmacro %}
{% macro display_icon(name) %}
<span class="glyphicon glyphicon-{{name}}" aria-hidden="true"></span>
{% endmacro %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Game</title>

		<link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
		<link href="{{url_for('static', filename='css/story_hero.css')}}" rel="stylesheet">
	</head>
	<body>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{{url_for('main.index')}}">Story Hero</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						{{display_nav_link('stories.list', 'Stories', 'book')}}
						{% if current_user.can(Permission.CREATE_STORY) %}
						{{display_nav_link('stories.new', 'Create story', 'pencil')}}
						{% endif %}
					</ul>
					<ul class="nav navbar-nav navbar-right">
						{% if current_user.is_authenticated %}
						{% if current_user.is_administrator() %}
						{{display_nav_link('users.list', 'Users', 'list')}}
						{% endif %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								{% if current_user.is_administrator() %}{{display_icon('flash')}}{% endif %}
								{{display_icon('user')}} {{current_user.username}}<span class="caret"></span></a>
							<ul class="dropdown-menu">
								{{display_nav_link('users.show', 'My profile', user_id = session['user_id'])}}
								{% if current_user.can(Permission.CREATE_STORY) %}
								{{display_nav_link('stories.user_stories', 'My stories')}}
								{% endif %}
								{{display_nav_link('stories.instances', 'Instances')}}
								<li role="separator" class="divider"></li>
								{{display_nav_link('auth.logout', 'Logout', 'log-out')}}
							</ul>
						</li>
						{% else %}
						{{display_nav_link('auth.register', 'Register')}}
						{{display_nav_link('auth.login', 'Login', 'log-in')}}
						{% endif %}
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
		{% if get_flashed_messages() %}
		<div class="messages">
			{% for category, message in get_flashed_messages(with_categories=true) %}
			{% if category == "info" %}
			{% set alert_class = "info" %}
			{% elif category == "warning" %}
			{% set alert_class = "warning" %}
			{% elif category == "error" %}
			{% set alert_class = "danger" %}
			{% else %}
			{% set alert_class = "success" %}
			{% endif %}
			<div class="alert alert-{{alert_class}} alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-close="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				{{message|safe}}
			</div>
			{% endfor %}
		</div>
		{% endif %}
		<div class="content">
			{% block content %}{% endblock %}
		</div>

		<script src="{{url_for('static', filename='js/jquery.min.js')}}"></script>
		<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
	</body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
<form action="{{url_for('login')}}" method="post">
	{{ form.csrf_token }}
	{{ form.username.label }} {{ form.username() }}
	<br />
	{{ form.password.label }} {{ form.password() }}
	<br />
	{{ form.remember_me.label }} {{ form.remember_me() }}
	<br />
	<button>Login</button>
</form>
{% endblock %}

app/templates/settings.html
{% extends "layout.html" %}
{% block content %}
<div>
	Logged as {{current_user.username}} ({{current_user.email}}) - <a href="{{url_for('auth.logout')}}">Logout</a>
</div>
<div>
	<ul>
		<li>is_authenticated = {{current_user.is_authenticated}}</li>
		<li>is_active = {{current_user.is_active}}</li>
		<li>is_anonymous = {{current_user.is_anonymous}}</li>
		<li>get_id = {{current_user.get_id()}}</li>
	</ul>
</div>
{% endblock %}

app/templates/users.html
{% extends "layout.html" %}
{% block content %}
		<div>
			<table class="table">
				<tr>
					<th>User</th>
					<th>Email</th>
					<th>Role</th>
					<th>Stories</th>
					<th>Actions</th>
				</tr>
				{% for user in users %}
					<tr>
						<td><a href="{{url_for('users.show', user_id = user.id)}}">{{user.username}}</a></td>
						<td>{{user.email}}</td>
						<td>{{user.role.name}}</td>
						<td><a href="{{url_for('stories.show', user_id = user.id)}}">{{user.stories|length}}</a></td>
						<td>
							<a href="{{url_for('users.edit', user_id = user.id)}}">Edit user {{display_icon('edit')}}</a><br />
							<a href="{{url_for('users.delete', user_id = user.id)}}">Delete user {{display_icon('remove')}}</a>
							{% if current_app.debug and current_user.is_administrator() %}
							<br /><a href="{{url_for('auth.login_username', user=user.username)}}">Login as {{user.username}} {{display_icon('log-in')}}</a>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</table>
		</div>
		<a href="{{url_for('users.add')}}">Add user</a>
{% endblock %}